# Generated by Django 4.1.3 on 2022-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='clientesactivos',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
