# Generated by Django 4.1.3 on 2022-11-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_clientes_estado_alter_clientes_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.DateField(auto_now_add=True)),
                ('horaEntrada', models.TimeField(auto_now_add=True)),
                ('fechaSalida', models.DateField(null=True)),
                ('horaSalida', models.TimeField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='backend.clientes')),
            ],
        ),
    ]
