# Generated by Django 4.1.3 on 2022-11-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientesActivos',
        ),
    ]
