# Generated by Django 4.1.3 on 2023-02-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_clientesactivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='userFoto',
            field=models.ImageField(null=True, upload_to='usersImages'),
        ),
    ]
